In [1]:
import numpy

### Crear un array desde 0 hasta un número dado por el usuario
**Enunciado:**
Pide al usuario un número `n` y crea un array que contenga los números desde 0 hasta `n` (inclusive).

**Visualización esperada:**
```
Ingrese un número entero: 5
Array generado: [0 1 2 3 4 5]
```

### Crear un array con N valores aleatorios entre 1 y 10
**Enunciado:**
Solicita al usuario cuántos valores quiere en su arreglo y genera números aleatorios entre 1 y 10.

**Visualización esperada:**
```
¿Cuántos valores quieres en el array? 4
Array con valores aleatorios: [3 9 1 7]
```

### Mostrar un subarray entre los índices 3 y 6 de un array de 20 elementos
**Enunciado:**
Crea un array de 20 números y muestra solo los valores entre los índices 3 y 6.

**Visualización esperada:**
```
Array completo: [ 0  1  2  3  4  5  6  7  8  9 ... 19]
Subarray del índice 3 al 6: [3 4 5 6]
```

### Crear una matriz de ceros con dimensiones dadas por el usuario
**Enunciado:**
El usuario debe ingresar el número de filas y columnas. Luego se crea una matriz de ceros de esas dimensiones.

**Visualización esperada:**
```
Ingrese el número de filas: 2
Ingrese el número de columnas: 3
Matriz de ceros:
[[0. 0. 0.]
 [0. 0. 0.]]
```

### Crear una matriz de nx5 donde cada fila tiene su número de fila
**Enunciado:**
La primera fila debe ser solo ceros, la segunda solo unos, y así sucesivamente.

**Visualización esperada:**
```
Ingrese el número de filas: 4
Matriz generada:
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
```

### Modificar un valor específico de una matriz 4x4
**Enunciado:**
Muestra la matriz generada, pide al usuario una posición y un nuevo valor para modificarla.

**Visualización esperada:**
```
Matriz original:
[[6 2 7 3]
 [1 8 4 9]
 [5 3 1 2]
 [7 6 4 5]]
Ingrese el índice de fila (0 a 3): 1
Ingrese el índice de columna (0 a 3): 2
Valor actual: 4
Ingrese el nuevo valor para esa posición: 0
Matriz modificada:
[[6 2 7 3]
 [1 8 0 9]
 [5 3 1 2]
 [7 6 4 5]]
```

### Crear una matriz cuadrada NxN llena con un número dado por el usuario
**Enunciado:**
Solicita el tamaño y el número que se repetirá en toda la matriz.

**Visualización esperada:**
```
Ingrese el valor de N: 3
Ingrese el número con el que llenar la matriz: 7
Matriz llena con el número 7
[[7 7 7]
 [7 7 7]
 [7 7 7]]
```

### Sumar dos matrices 3x3 y encontrar posiciones donde la suma es 10
**Enunciado:**
Genera dos matrices aleatorias sin repetición y encuentra las posiciones cuya suma sea 10.

**Visualización esperada:**
```
Matriz 1:
[[3 2 4]
 [1 5 7]
 [8 6 9]]
Matriz 2:
[[2 8 3]
 [9 4 6]
 [7 5 1]]
Suma de matrices:
[[5 10 7]
 [10 9 13]
 [15 11 10]]
Posiciones donde la suma es 10:
[[ False  True  False]
 [ True  False  False]
 [ False  False  True]]
```

### Crear una matriz complementaria que al sumarse con otra dé todos valores iguales a 10
**Enunciado:**
Usa una matriz fija y genera una segunda matriz que complemente cada valor para llegar a 10.

**Visualización esperada:**
```
Matriz 1:
[[1 3 2]
 [6 5 4]
 [7 9 8]]
Matriz complementaria (Matriz 2):
[[9 7 8]
 [4 5 6]
 [3 1 2]]
Suma:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
```