# Comandos con NumPy
Explorando creación y manipulación de arreglos y matrices.

### 1. Crear un array y matriz de ceros

In [1]:

import numpy as np

# Crear un array de 5 ceros
a = np.zeros(5)
print("Array de ceros:", a)

# Crear una matriz de 2x2 llena de ceros
m = np.zeros((2, 2))
print("Matriz 2x2 de ceros:\n", m)


Array de ceros: [0. 0. 0. 0. 0.]
Matriz 2x2 de ceros:
 [[0. 0.]
 [0. 0.]]


### 2. Crear un array y matriz de unos

In [2]:

# Crear un array de 5 unos
a = np.ones(5)
print("Array de unos:", a)

# Crear una matriz de 2x2 llena de unos
m = np.ones((2, 2))
print("Matriz 2x2 de unos:\n", m)


Array de unos: [1. 1. 1. 1. 1.]
Matriz 2x2 de unos:
 [[1. 1.]
 [1. 1.]]


### 3. Crear un array y matriz con un número fijo (por ejemplo, 7)

In [3]:

# Crear un array de 5 sietes
a = np.full(5, 7)
print("Array de sietes:", a)

# Crear una matriz 2x2 llena de sietes
m = np.full((2, 2), 7)
print("Matriz 2x2 de sietes:\n", m)


Array de sietes: [7 7 7 7 7]
Matriz 2x2 de sietes:
 [[7 7]
 [7 7]]


### 4. Crear un array y matriz de números del `n` al `m` usando `arange`

In [4]:

# Definir los extremos
n = 1
m = 26

# Crear un array del 1 al 25 (excluye el 26)
a = np.arange(n, m)
print("Array con range:", a)

# Convertir el array en una matriz 5x5
matriz = a.reshape((5, 5))
print("Matriz 5x5 con range:\n", matriz)


Array con range: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Matriz 5x5 con range:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### 5. Lo mismo pero mezclando el orden con `shuffle`

In [5]:

# Crear el mismo array del 1 al 25
a = np.arange(1, 26)

# Mezclar el array en orden aleatorio
np.random.shuffle(a)
print("Array mezclado:", a)

# Convertirlo en una matriz 5x5 aleatoria
matriz = a.reshape((5, 5))
print("Matriz 5x5 mezclada:\n", matriz)


Array mezclado: [ 7 15 24 14  6 21 13 18  2  8  4 25 23 12  3 10 19 20 17  9  5 11 16  1
 22]
Matriz 5x5 mezclada:
 [[ 7 15 24 14  6]
 [21 13 18  2  8]
 [ 4 25 23 12  3]
 [10 19 20 17  9]
 [ 5 11 16  1 22]]


### 6. Crear array duplicado (1,1,2,2,...6,6) y pasarlo a matriz

In [ ]:

# Usamos np.repeat para duplicar valores
# np.arange(1, 7) genera [1, 2, 3, 4, 5, 6]
# np.repeat(..., 2) duplica cada elemento → [1,1,2,2,...,6,6]
a = np.repeat(np.arange(1, 7), 2)
print("Array duplicado:", a)

# Convertimos a matriz. Tiene 12 elementos, así que puede ser 3x4, 2x6, 6x2, etc.
matriz = a.reshape((3, 4))
print("Matriz duplicada (3x4):\n", matriz)

# Si quisieras duplicar cada número 3 veces: np.repeat(np.arange(1, 7), 3)
# Solo asegúrate de que el total de elementos sea divisible por las dimensiones de la matriz


### 7. Duplicado mezclado con `shuffle`

In [ ]:

# Crear el array duplicado
a = np.repeat(np.arange(1, 7), 2)

# Mezclarlo de forma aleatoria
np.random.shuffle(a)
print("Array duplicado y mezclado:", a)

# Convertirlo a matriz 3x4
matriz = a.reshape((3, 4))
print("Matriz duplicada y mezclada:\n", matriz)


### 8. Selección de partes de una matriz 10x10 con slicing `[i:j, x:y]`

In [ ]:

# Crear matriz 10x10 con valores del 0 al 99
m = np.arange(100).reshape((10, 10))
print("Matriz 10x10:\n", m)

# En NumPy, cuando usamos m[i:j, x:y],
# significa: seleccionar desde la fila i hasta la fila j **sin incluir j**,
# y desde la columna x hasta la columna y **sin incluir y**.

# Ejemplo 1: esquina superior izquierda
print("Ejemplo 1 (0:3, 0:3):\n", m[0:3, 0:3])

# Ejemplo 2: parte central
print("Ejemplo 2 (5:8, 5:8):\n", m[5:8, 5:8])

# Ejemplo 3: esquina inferior izquierda
print("Ejemplo 3 (7:10, 0:3):\n", m[7:10, 0:3])

# Ejemplo 4: borde superior derecho
print("Ejemplo 4 (0:5, 5:10):\n", m[0:5, 5:10])

# Ejemplo 5: submatriz intermedia
print("Ejemplo 5 (3:7, 2:6):\n", m[3:7, 2:6])
