### Ejercicio 1: Matriz con Diagonal Principal de Puros Unos

Implemente un programa en Python que genere matrices aleatorias de tamaño 5x5 (debe funcionar para cualquier tamaño de matriz) utilizando solamente valores 0 y 1. El objetivo es repetir la generación hasta que la diagonal principal esté compuesta completamente por unos (1).

Para esto, se recomienda utilizar la función `np.random.randint` para generar la matriz y un ciclo `while` que repita la generación hasta que se cumpla la condición de tener cinco unos en las posiciones.

El programa debe mostrar la cantidad de intentos realizados y la matriz final válida.


In [ ]:
import numpy as np

### Ejercicio 2: Generación Aleatoria de la Letra N

Cree un programa que genere matrices de tamaño 5x5 (debe ser para cualquier matriz de NxN) con números 0 y 1 de manera aleatoria, utilizando un ciclo `while`, hasta que se forme correctamente la letra **N**.

La letra **N** debe estar representada por:

- La primera columna con solo 1s.
- La última columna con solo 1s.
- La diagonal principal con solo 1s.

No importa si otras posiciones de la matriz contienen unos o ceros. Solo se deben verificar esas tres condiciones estructurales.


In [ ]:
import numpy as np

### Ejercicio 3: Construcción de la Letra M

Implemente un programa que construya una matriz de tamaño 5x5 (debe ser para cualquier matriz de NxN) que represente la letra **M** utilizando valores 1 y 0.

La letra **M** debe tener:

- Primera y última columnas con puros 1s.
- Dos diagonales que convergen en la posición central (2,2) o (n/2,n/2), que también debe contener un 1.

Puede hacerlo directamente sin aleatoriedad o usar `np.zeros()` e insertar manualmente los 1 en las posiciones necesarias.


In [3]:
import numpy as np

[[1 1 0 1 1]
 [1 0 1 0 1]
 [1 1 0 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]]


### Ejercicio 4: Construcción de la Letra E

Cree un programa que genere una matriz 5x5 (debe ser para cualquier matriz de NxN) que represente la letra **E** utilizando valores 0 y 1. Para que la letra esté bien formada, la matriz debe cumplir con las siguientes condiciones:

- La primera columna debe tener únicamente 1.
- Las filas 0, 2 y 4 deben estar completamente llenas de 1.



In [4]:
import numpy as np

[[1 1 1 1 1]
 [1 0 0 0 0]
 [1 1 1 1 1]
 [1 0 0 0 0]
 [1 1 1 1 1]]
