### Ejercicio 1: Tic Tac Toe (3 en línea)

El clásico juego de 3 en línea se juega en un tablero de 3x3, donde dos jugadores (X y O) se turnan para colocar sus símbolos. El objetivo es formar una línea horizontal, vertical o diagonal con tres símbolos iguales.

En este ejercicio se entrega la función `marcar_jugada(tablero, fila, columna, jugador)` que permite ingresar una jugada válida en el tablero, y `mostrar_tablero(tablero)` que imprime el tablero de forma clara.

El objetivo del estudiante es implementar la función `verificar_victoria(tablero)` que, dado un tablero de juego, indique si algún jugador ha ganado.

Ejemplo de juego funcionando:

Jugador X elige (0, 0)  
Jugador O elige (1, 1)  
Jugador X elige (0, 1)  
Jugador O elige (2, 2)  
Jugador X elige (0, 2)  

Tablero final:

```
X | X | X  
- | O | -  
- | - | O
```

Ganador: X


In [ ]:
import numpy as np

def crear_tablero():
    return np.full((3, 3), '-')

def mostrar_tablero(tablero):
    for fila in tablero:
        print(' | '.join(fila))
    print()

def marcar_jugada(tablero, fila, columna, jugador):
    if tablero[fila, columna] == '-':
        tablero[fila, columna] = jugador
    else:
        print("Espacio ocupado. Elija otra posición.")

# Función a completar
def verificar_victoria(tablero):
    # Escribir Código
    pass

tablero = crear_tablero()

mostrar_tablero(tablero)

### Ejercicio 2: Batalla Naval Clásico

Se debe implementar una versión simplificada del juego Batalla Naval. El tablero es una matriz 5x5. Se entrega una función `crear_tablero()` que crea el tablero con barcos ocultos y `imprimir_tablero(tablero, revelar=False)` que imprime el tablero actual (sin mostrar los barcos si `revelar=False`).

El estudiante debe implementar:

- `atacar(tablero, fila, columna)`: devuelve si fue un "Hit" o "Miss" y actualiza el tablero.
- `juego_terminado(tablero)`: verifica si todos los barcos fueron hundidos.

Ejemplo de interacción esperada:

```
Ataque en (2, 3): Miss  
Ataque en (4, 0): Hit  
Ataque en (1, 1): Hit  

Tablero actual:
~ ~ ~ ~ ~  
~ X ~ ~ ~  
~ ~ ~ O ~  
~ ~ ~ ~ ~  
X ~ ~ ~ ~

Barcos restantes: 0  
¡Juego terminado!
```

(X representa un barco impactado, O representa agua fallida)


In [2]:
import numpy as np

def crear_tablero():
    tablero = np.full((5, 5), '~')
    # Barcos marcados con 'B' (no visibles por defecto)
    posiciones_barcos = [(1, 1), (4, 0)]
    for f, c in posiciones_barcos:
        tablero[f, c] = 'B'
    return tablero

def imprimir_tablero(tablero, revelar=False):
    for fila in tablero:
        if revelar:
            print(' '.join(fila))
        else:
            print(' '.join(['~' if x == 'B' else x for x in fila]))
    print()

# Funciones a completar
def atacar(tablero, fila, columna):
    # Escribir Código
    pass

def juego_terminado(tablero):
    # Escribir Código
    pass

tablero = crear_tablero()

mostrar_tablero(tablero)

~ | ~ | ~ | ~ | ~
~ | B | ~ | ~ | ~
~ | ~ | ~ | ~ | ~
~ | ~ | ~ | ~ | ~
B | ~ | ~ | ~ | ~



### Ejercicio 3: Sudoku 4x4

El Sudoku 4x4 es una versión reducida del juego de lógica en el que cada fila, columna y subcuadro de 2x2 debe contener los números del 1 al 4 sin repetirse.

Se entrega:

- `imprimir_tablero(tablero)`: imprime el tablero actual.
- `verificar_fila(tablero, fila)`: indica si una fila tiene números duplicados o fuera de rango.

El estudiante debe implementar:

- `verificar_cuadrante(tablero, fila_base, col_base)`: verifica si el subcuadro 2x2 desde esa posición es válido.
- `verificar_sudoku(tablero)`: verifica si todo el tablero es válido (filas, columnas y cuadrantes).

Ejemplo de tablero válido:

```
[1 2 3 4]  
[3 4 1 2]  
[2 1 4 3]  
[4 3 2 1]

Resultado: Sudoku válido.
```


In [ ]:
import numpy as np

def imprimir_tablero(tablero):
    for fila in tablero:
        print(fila)

def verificar_fila(tablero, fila):
    valores = tablero[fila]
    return set(valores) == set([1, 2, 3, 4])

# Funciones a completar
def verificar_cuadrante(tablero, fila_base, col_base):
    # Escribir Código
    pass

def verificar_sudoku(tablero):
    # Escribir Código
    pass

tablero = [[1,2,3,4],[3,4,1,2],[2,1,4,3],[4,3,2,1]]

imprimir_tablero(tablero)

print(verificar_fila(tablero,0))
