
# Repaso de NumPy: Manipulación de Tableros

## 1. ¿Qué es NumPy?

NumPy (Numerical Python) es una de las bibliotecas fundamentales en Python para el cálculo numérico. Su principal ventaja es la eficiencia en el manejo de arreglos y operaciones vectorizadas, siendo mucho más veloz que listas anidadas tradicionales de Python.

La estructura base de NumPy es el `ndarray`, un arreglo n-dimensional que puede usarse para representar vectores, matrices y estructuras más complejas. Esto lo convierte en una herramienta ideal para trabajar con estructuras como tableros, mapas y juegos.

### Diferencias con las listas tradicionales:

- Las listas de Python permiten contener distintos tipos de datos, mientras que los `ndarray` de NumPy son homogéneos.
- Las operaciones en listas se hacen con ciclos; en NumPy se vectorizan (son más rápidas y concisas).
- NumPy tiene acceso a funciones avanzadas como estadísticas, transformaciones y manipulación de dimensiones.

## 2. Importación y creación de arrays



In [ ]:
import numpy as np



### Arrays de 1 dimensión



In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]



### Arrays de 2 dimensiones (matriz)



In [ ]:
matriz = np.array([[1, 2], [3, 4]])
print(matriz)



### Visualización con shape



In [ ]:
print("Dimensiones:", matriz.shape)



## 3. Acceso por índices y recorrido

Acceder a un elemento y recorrer la matriz:



In [ ]:
print(matriz)

print()

print(matriz[0][1])  # Resultado: 2

print()

for fila in matriz:
    for elemento in fila:
        print(elemento)



## 4. Casillas vecinas (modelo tablero)

Este ejercicio muestra cómo revisar las casillas vecinas (arriba, abajo, izquierda, derecha y diagonales) de una celda específica sin salir de los límites de la matriz.



In [ ]:
matriz = np.array([
    [2, 3, 0, 4, 0],
    [0, 1, 1, 1, 1],
    [1, 2, 4, 2, 0],
    [4, 3, 2, 3, 2],
    [1, 1, 1, 3, 3]
])

print(matriz)

print()

i = 1
j = 1
print(matriz[i,j])

print()

for dx in [-1, 0, 1]:
    for dy in [-1, 0, 1]:
        if dx == 0 and dy == 0:
            print("x",end=" ")
            continue
        ni = i + dx
        nj = j + dy
        if 0 <= ni and ni < matriz.shape[0] and 0 <= nj and nj < matriz.shape[1]:
            print(matriz[ni,nj],end=" ")
    print()


[[2 3 0 4 0]
 [0 1 1 1 1]
 [1 2 4 2 0]
 [4 3 2 3 2]
 [1 1 1 3 3]]

1

2 3 0 
0 x 1 
1 2 4 



## 5. Ejercicio: Encontrar el número más grande

Usando dos ciclos `for`, buscamos el número máximo en una matriz sin usar funciones de NumPy.



In [ ]:
matriz = np.array([
    [2, 8, 5],
    [4, 1, 9],
    [3, 7, 6]
])

maximo = matriz[0][0]

for fila in matriz:
    for valor in fila:
        if valor > maximo:
            maximo = valor

print("El valor máximo es:", maximo)



## 6. Crear tablero con 1s y 0s aleatorios

Creamos una lista de valores y la convertimos en una matriz de 5x5 donde hay exactamente 5 unos y 20 ceros.



In [ ]:
import random
n1 = 5
n2 = 20
valores = []

for i in range(5):
  valores.append(1)

for i in range(20):
  valores.append(0)

print(valores)

print()

random.shuffle(valores)

print(valores)

print()

matriz = np.array(valores)

print(matriz)

print()

matriz = matriz.reshape((5, 5))

print(matriz)



## 7. Casos de borde: sumar celdas vecinas

Contamos la cantidad de `1`s que rodean cada celda, verificando bordes para no salir de la matriz.



In [ ]:
matriz = np.random.randint(0, 2, (5, 5))

print(matriz)

for i in range(5):
    for j in range(5):
        suma = 0
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                ni, nj = i + dx, j + dy
                if 0 <= ni < 5 and 0 <= nj < 5 and not (dx == 0 and dy == 0):
                    suma += matriz[ni][nj]
        print(f"Suma alrededor de ({i},{j}) = {suma}")
