# Guía de Ejercicios con NumPy
Ejercicios prácticos para trabajar con matrices en Python usando NumPy.

## Verificar diagonales que suman un número par
**Objetivo**: Analizar sumas diagonales y aplicar filtros.

**Enunciado**:
Crea una matriz 5x5 con valores aleatorios del 1 al 9. Para cada celda, calcula la suma de sus diagonales inmediatas (↖️, ↗️, ↙️, ↘️). Si la suma es un número par, imprímela junto a su posición.

In [ ]:
import numpy as np

matriz = np.random.randint(1, 10, (5, 5))
print("Matriz generada:\n", matriz)




Matriz generada:
 [[8 4 5 5 7]
 [4 4 3 2 6]
 [5 8 4 8 5]
 [2 3 4 1 5]
 [1 8 9 8 6]]


## Validar celdas antes de reemplazo
**Objetivo**: Verificar bordes y ocupación de celdas.

**Enunciado**:
Crea una matriz 6x6 con ceros. Permite al usuario ingresar 5 coordenadas (fila, columna, valor). Si la coordenada está fuera de rango o la celda ya está ocupada, muestra un mensaje de error.

In [ ]:
matriz = np.zeros((6, 6), dtype=int)

print(matriz)


## Simulación del buscaminas
**Objetivo**: Simular una matriz con minas y contar minas vecinas.

**Enunciado**:
Crea una matriz 8x8 con 10 minas (valor 1) distribuidas aleatoriamente. Luego, reemplaza las demás celdas con el número de minas vecinas.

In [ ]:
import random

valores = [1]*10 + [0]*54
random.shuffle(valores)
tablero = np.array(valores).reshape((8, 8))
resultado = np.zeros((8, 8), dtype=int)

print(resultado)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


## Simular caída de fichas
**Objetivo**: Simular caída vertical como en 4 en línea.

**Enunciado**:
Crea una matriz 6x6 con ceros. Pide al usuario elegir una columna y coloca un 1 en la fila más baja disponible.

In [ ]:
matriz = np.zeros((6, 6), dtype=int)
print(matriz)



## Contar elementos mayores que un valor
**Objetivo**: Filtrar elementos según condición.

**Enunciado**:
Crea una matriz 4x4 con valores del 1 al 20. Imprime los elementos mayores a 15.

In [ ]:
matriz = np.random.randint(1, 21, (4, 4))
print("Matriz generada:\n", matriz)




## Rellenar columna con validaciones
**Objetivo**: Rellenar celdas evitando repeticiones y errores de rango.

**Enunciado**:
Crea una matriz 5x5 con ceros. Pide al usuario ingresar fila y columna. Si la celda está fuera del rango o ya fue usada, muestra un error.

In [ ]:
matriz = np.zeros((5, 5), dtype=int)
print(matriz)


## Recorrer matriz y contar múltiplos de 7
**Objetivo**: Aplicar condición sobre todos los elementos de una matriz.

**Enunciado**:
Crea una matriz 6x6 con valores entre 1 y 50. Imprime solo los que son múltiplos de 7.

In [ ]:
matriz = np.random.randint(1, 51, (6, 6))
print("Matriz generada:\n", matriz)


## Verificar diagonales vecinas que sumen más de 10
**Objetivo**: Verificar las diagonales inmediatas y aplicar un umbral.

**Enunciado**:
Crea una matriz 7x7 con valores entre 1 y 9. Para cada celda, revisa las diagonales y muestra cuántas de ellas tienen suma mayor a 10.

In [ ]:
matriz = np.random.randint(1, 10, (7, 7))
print("Matriz generada:\n", matriz)
