# Guía de Ejercicios Básicos de NumPy

## Ejercicio 1
**Enunciado**: Cree una matriz de 5x5 con puros ceros

## Ejercicio 2
**Enunciado**: Cree una matriz de 6x6 con puros unos

## Ejercicio 3
**Enunciado**: Cree una matriz de 7x7 llena con números N, que es un valor dado por el usuario

## Ejercicio 4
**Enunciado**: Cree una matriz de MxM con M dado por el usuario con números entre a y b, también dados por el usuario

## Ejercicio 5
**Enunciado**: Cree una matriz de 10x10 siendo la mitad 1 y la otra mitad 2

## Ejercicio 6
**Enunciado**: Crea un mapa de 10x10 donde los 0 son tierra, los 1 son plantas y los 2 son animales (60, 30, 10 elementos respectivamente)

## Ejercicio 7
**Enunciado**: Cree una matriz de 10x10 con ceros. El usuario entrega coordenadas i,j y aumenta en uno la posición. Repite mostrando la matriz.

## Ejercicio 8
**Enunciado**: Cree una matriz de 10x10 con ceros. El usuario entrega una fila que se incrementa en 1 cada vez que se selecciona.

## Ejercicio 9
**Enunciado**: Cree una matriz NxN donde cada fila tenga números aleatorios entre 1 y 7. El usuario da el valor de N (no usar NumPy directamente).

## Ejercicio 10
**Enunciado**: Cree una matriz de 10x10. Luego pida nuevas dimensiones x,y. Hacer reshape si x*y=100. Si x=0, y=0 termina.

## Ejercicio 11
**Enunciado**: Cree una letra (A, E, I, F, G, X) en una matriz NxN. El usuario entrega el tamaño. Mostrar cómo se ven por pantalla.



```
*****
*   *
*****
*   *
*   *

```



```
*****
*    
*****
*    
*****

```



```
*****
  *  
  *  
  *  
*****

```

```
*****
*    
*****
*    
*    

```

```
 ****
*    
* ***
*   *
 ****

```

```
*   *
 * *
  *  
 * *
*   *
```

## Ejercicio 12
**Enunciado**: Crea un programa que genere una matriz de tamaño N x N, donde N es entregado por el usuario. Luego, el programa solicitará una serie de números que el usuario quiere que se repitan cierta cantidad de veces dentro de esa matriz.

El objetivo es llenar completamente la matriz con los números proporcionados. El programa debe validar que no se agregue más de lo que cabe, y permitir terminar anticipadamente escribiendo 0. Al final, se mostrará la matriz en forma ordenada (según el orden de ingreso) y en forma aleatoria.
Objetivo:

    Reforzar el uso de listas, input(), estructuras while, reshape() y aleatorización.

    Trabajar el control de flujo con validación de entradas.




```
Ingrese N para la matriz NxN: 3
Quedan 9 espacios disponibles.
Número a ingresar (0 para terminar): 5
¿Cuántas veces quieres que aparezca el número 5?: 4
Quedan 5 espacios disponibles.
Número a ingresar (0 para terminar): 1
¿Cuántas veces quieres que aparezca el número 1?: 2
Quedan 3 espacios disponibles.
Número a ingresar (0 para terminar): 9
¿Cuántas veces quieres que aparezca el número 9?: 3

Matriz ordenada según el ingreso de datos:
[[5 5 5]
 [5 1 1]
 [9 9 9]]

Matriz aleatoria:
[[1 5 9]
 [5 5 1]
 [9 9 5]]

```

