## ¿Qué es NumPy?

**NumPy** (*Numerical Python*) es una librería fundamental de Python diseñada para la computación científica y numérica. Su objetivo principal es proporcionar una estructura de datos poderosa llamada `ndarray` que permite trabajar con arreglos (vectores y matrices) de manera mucho más rápida y eficiente que las listas tradicionales de Python.

---

### ¿Por qué usar NumPy y no solo listas?

Las listas de Python son muy versátiles, pero cuando se trata de realizar cálculos matemáticos complejos, NumPy ofrece ventajas clave:

| Característica             | Listas de Python        | NumPy ndarray                  |
|---------------------------|-------------------------|--------------------------------|
| Tipado de datos           | Mezcla de tipos         | Homogéneo (todos del mismo tipo) |
| Velocidad                 | Más lenta               | Más rápida (escrita en C)      |
| Operaciones vectorizadas  | No (requiere bucles)    | Sí (uso directo de operadores) |
| Uso de memoria            | Mayor                   | Optimizado y menor             |
| Funcionalidad matemática  | Limitada                | Ampliamente soportada          |

---

### ¿Qué se puede hacer con NumPy?

NumPy es ideal para:

- Operaciones matemáticas con vectores y matrices.
- Álgebra lineal.
- Estadística y análisis de datos.
- Transformaciones geométricas.
- Generación de números aleatorios.
- Preparación de datos para machine learning.

---

### Estructura principal: `ndarray`

Un **ndarray** (n-dimensional array) es como una lista de listas (o una tabla), pero mucho más eficiente.

#### Ejemplo:
```python
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

```

```python
[[1 2 3]
 [4 5 6]]

```


## ¿Por qué usar NumPy?
- Es más **rápido y eficiente** que las listas de Python puras.
- Soporta **operaciones vectorizadas** sin necesidad de bucles.
- Ideal para estructuras como tableros, imágenes, grillas, cronómetros, etc.

In [ ]:
# Importar NumPy
import numpy as np

In [ ]:
vector1 = [1,2,3]
vector2 = [4,5,6]

print(vector1)
print(vector2)

pp = 0
for i in range(len(vector1)):
  pp = pp + vector1[i]*vector2[i]
print(pp)

matriz = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]

for fila in matriz:
  print(fila)
print()

nvector1 = np.array([1,2,3])
nvector2 = np.array(vector2)
print(nvector1)
print(nvector2)

print(np.dot(nvector1,nvector2))
print(np.cross(nvector1,nvector2))

print()
nmatriz = np.array(matriz)
print(nmatriz)

[1, 2, 3]
[4, 5, 6]
32
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

[1 2 3]
[4 5 6]
32
[-3  6 -3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 1. Creación de Arrays

### Explicación

Un **array** en NumPy es como una lista de Python, pero optimizada para operaciones matemáticas vectorizadas. Se crea utilizando `np.array()`.

### Ejemplos

In [ ]:
import numpy as np

# Ejemplo 1: Array unidimensional
arr1 = np.array([1, 2, 3, 4])
print(arr1)

print()

# Ejemplo 2: Array bidimensional (matriz)
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1+v2)

lista1 = [1,2,3,4]
lista2 = [5,6,7,8]

print(lista1+lista2)

print(v1*2)
print(lista1*2)



[ 6  8 10 12]
[1, 2, 3, 4, 5, 6, 7, 8]
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
v = np.array([[1,2,3,4,10],[5,6,7,8,12,4]])

print(v)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

## 2. Operaciones Matemáticas

### Explicación

NumPy permite realizar operaciones aritméticas directamente entre arrays, elemento a elemento.

### Ejemplos

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Ejemplo 1: Suma
print(a + b)

print()

# Ejemplo 2: Potencia
print(a ** 2)

[5 7 9]

[1 4 9]


## 3. Manipulación de Formas

### Explicación

Puedes cambiar la forma (shape) de un array con `.reshape()`, por ejemplo, de 1D a 2D.

In [ ]:
# Ejemplo 1: Cambiar de forma
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
print(a.shape)
print()
b = a.reshape((2, 3))
print(b)
print(b.shape)

print()
b = a.reshape((3, 2))
print(b)
print(b.shape)


print()
b = a.reshape((6, 1))
print(b)
print(b.shape)


print()

# Ejemplo 2: Convertir en una sola fila
c = b.reshape((1, 6))
print(c)

[1 2 3 4 5 6]
(6,)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)

[[1 2 3 4 5 6]]


## 4. Estadísticas Básicas

### Explicación

NumPy facilita el cálculo de estadísticas como la media, desviación estándar, suma, máximo y mínimo.


In [ ]:
a = np.array([10, 20, 30, 40, 50])

# Ejemplo 1: Promedio
print(np.mean(a))

print()

# Ejemplo 2: Desviación estándar
print(np.std(a))

30.0

14.142135623730951


## 5. Acceso por Índices

### Explicación

Puedes acceder a los elementos de un array con índices como en una lista, y también usar slicing (`:`).

### Ejemplos

In [ ]:
a = np.array([[1, 2, 3,2,1,2,4,7,1,9], [4, 5, 6,2,1,1,2,3,1,1], [9, 5, 3,2,1,7,2,3,1,1]])
print(a)
# Ejemplo 1: Acceder al elemento (1,2)
print(a[1][2])
print(a[1,2])

print()

print(a[0,:2])
print(a[0:2,2:6])

[[1 2 3 2 1 2 4 7 1 9]
 [4 5 6 2 1 1 2 3 1 1]
 [9 5 3 2 1 7 2 3 1 1]]
6
6

[1 2]
[[3 2 1 2]
 [6 2 1 1]]


## 6. Generación de Arrays y Matrices con 0, 1 o un número

### Explicación

NumPy tiene funciones especiales como `np.zeros()`, `np.ones()`, `np.full()` para crear arrays con valores específicos.

### Ejemplos

In [ ]:
# Ejemplo 1: Crear array de ceros
a = np.zeros(5)
print(a)

print()

# Ejemplo 2: Crear array lleno con el número 7
b = np.full(4, 7)
print(b)

In [ ]:
import numpy as np

lista = []
for i in range(10):
  lista2 = []
  for j in range(10):
    lista2.append(0)
  lista.append(lista2)

for fila in lista:
  print(fila)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
import numpy as np

lista = np.zeros([10,10])
print(lista)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np

lista = np.full([6,6],"#")
print(lista)

[['#' '#' '#' '#' '#' '#']
 ['#' '#' '#' '#' '#' '#']
 ['#' '#' '#' '#' '#' '#']
 ['#' '#' '#' '#' '#' '#']
 ['#' '#' '#' '#' '#' '#']
 ['#' '#' '#' '#' '#' '#']]


## 7. Generación de Matrices con 0, 1 o un número

### Explicación

También puedes generar matrices (arrays 2D) con los mismos valores.

### Ejemplos

In [ ]:
# Ejemplo 1: Matriz de 3x3 con unos
a = np.zeros((3, 3))
print(a)

print()

# Ejemplo 2: Matriz de 2x4 con valor 9
b = np.full((2, 4), 9)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[9 9 9 9]
 [9 9 9 9]]


## 8. Convertir Arrays en Matrices

### Explicación

Puedes convertir listas o arrays unidimensionales en matrices 2D usando `.reshape()` o pasando listas de listas.

### Ejemplos

In [ ]:
# Ejemplo 1: Lista a matriz
lista = [1, 2, 3, 4, 5, 6]
matriz = np.array(lista).reshape((2, 3))
print(matriz)

print()

# Ejemplo 2: De array 1D a 2D fila
a = np.array([7, 8, 9])
print(a.reshape((1, 3)))

[[1 2 3]
 [4 5 6]]

[[7 8 9]]


## 9. Propiedades útiles: `.shape`, `.dtype`, `.size`, `.ndim`

### Explicación

Estas propiedades permiten obtener información clave sobre el array:

- `.shape`: Dimensiones (filas, columnas)
- `.dtype`: Tipo de dato (int, float, etc.)
- `.size`: Total de elementos
- `.ndim`: Número de dimensiones


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = np.zeros([3,3,3])
print(a)
print(a.shape)
print(a.shape[0])
print(a.shape[1])
print(a.dtype)
print(a.size)
print(a.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(3, 3, 3)
3
3
float64
27
3


Cuando trabajamos con matrices (o arreglos bidimensionales), el uso de ciclos `for` anidados permite recorrer, modificar o construir estructuras complejas. Con NumPy, esta tarea se hace aún más eficiente y poderosa.

## Creación de matrices con valores específicos

### `np.zeros()` — Crear una matriz llena de ceros


In [ ]:
import numpy as np
matriz_ceros = np.zeros((4, 5), dtype=int)
print(matriz_ceros)

### `np.ones()` — Crear una matriz llena de unos

In [ ]:
matriz_unos = np.ones((3, 3), dtype=int)
print(matriz_unos)

### `np.full()` — Crear una matriz con un valor específico

In [ ]:
matriz_fijos = np.full((2, 4), 7)
print(matriz_fijos)

[[7 7 7 7]
 [7 7 7 7]]


### `np.random.randint()` — Crear una matriz con números aleatorios enteros

In [ ]:
matriz_random = np.random.randint(1, 10, size=(20, 20))
print(matriz_random)

[[4 2 3 3 8 6 8 3 8 6 5 2 5 9 8 7 2 6 3 8]
 [6 6 3 1 2 3 9 7 2 9 3 4 2 8 3 1 8 9 3 4]
 [9 4 6 5 4 4 9 1 2 4 9 1 2 2 8 7 3 1 5 7]
 [1 8 6 7 7 4 3 5 8 4 6 3 3 5 3 3 8 1 1 4]
 [4 4 7 4 2 7 8 2 4 4 5 1 1 4 9 2 5 4 6 8]
 [2 4 7 3 5 8 4 5 8 5 7 2 8 2 2 9 8 8 7 1]
 [4 7 3 4 2 4 6 8 3 8 9 4 2 9 2 7 3 6 7 4]
 [6 9 7 2 2 1 3 4 4 9 7 2 5 4 4 7 8 3 5 9]
 [4 8 6 7 8 9 8 1 9 8 3 8 1 6 8 8 4 6 2 2]
 [4 9 3 5 5 9 6 8 9 5 6 6 1 3 8 3 7 7 5 4]
 [9 1 7 4 7 2 6 5 7 2 8 2 5 4 5 5 6 6 1 1]
 [8 8 2 9 3 8 6 8 1 3 2 5 5 5 6 2 4 6 6 2]
 [4 9 7 9 2 7 9 6 2 4 8 4 7 9 2 9 8 9 5 4]
 [8 6 6 9 6 7 6 6 2 3 1 1 5 5 8 9 7 9 7 8]
 [1 1 5 6 5 4 1 8 6 7 6 3 3 6 7 1 1 4 8 3]
 [5 7 4 3 9 2 3 6 7 9 3 6 1 5 6 1 7 1 6 3]
 [4 9 9 5 7 5 8 2 9 6 9 1 6 2 6 4 4 1 4 9]
 [4 2 6 3 9 4 9 4 1 3 8 2 7 5 2 9 7 7 4 5]
 [7 6 2 8 9 7 1 2 1 4 7 4 8 9 8 9 4 7 6 9]
 [3 7 8 7 3 2 6 9 3 7 5 6 6 3 6 8 2 1 3 7]]


## Uso de ciclos `for` para recorrer o modificar matrices

### Ejemplo 1: Recorrer todos los elementos

In [ ]:
matriz = np.array([[1, 2], [3, 4]])
print(matriz)
for fila in matriz:
    for valor in fila:
        print(valor, end=' ')

[[1 2]
 [3 4]]
1 2 3 4 

### Ejemplo 2: Reemplazar todos los valores impares por 0

In [ ]:
matriz = np.random.randint(1, 10, size=(7, 8))
print(matriz)

for x in range(matriz.shape[0]):
    for y in range(matriz.shape[1]):
        if matriz[x,y] % 2 == 0:
            matriz[x,y] = 0
print(matriz)

[[9 8 9 5 3 3 3 1]
 [5 6 2 9 4 3 4 7]
 [4 6 1 6 5 9 9 7]
 [7 8 7 6 1 3 4 3]
 [5 9 8 8 8 7 5 9]
 [8 9 1 5 8 1 6 5]
 [8 3 5 5 6 8 1 4]]
[[9 0 9 5 3 3 3 1]
 [5 0 0 9 0 3 0 7]
 [0 0 1 0 5 9 9 7]
 [7 0 7 0 1 3 0 3]
 [5 9 0 0 0 7 5 9]
 [0 9 1 5 0 1 0 5]
 [0 3 5 5 0 0 1 0]]


## Crear una matriz que dibuje una letra "O"

Queremos una matriz de `n x n` con 1 en los bordes y 0 en el centro, simulando la letra O.

### Ejemplo 1: Tamaño 5x5


In [ ]:
n = 5
o = np.ones((n, n), dtype=int)
for i in range(1, n - 1):
    for j in range(1, n - 1):
        o[i, j] = 0
print(o)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Ejemplo 2: Tamaño 7x7




In [ ]:
n = 7
o = np.ones((n, n), dtype=int)
for i in range(1, n - 1):
    for j in range(1, n - 1):
        o[i, j] = 0
print(o)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


### Ejemplo 2: Tamaño NxN

In [ ]:
n = int(input())
o = np.ones((n, n), dtype=int)
for i in range(1, n - 1):
    for j in range(1, n - 1):
        o[i, j] = 0
print(o)

In [ ]:
n = int(input())

o = np.zeros((n,n),dtype=int)
print(o)

for i in range(o.shape[0]):
  for j in range(o.shape[0]):
    if i > 0 and i < n-1 and j > 0 and j < n-1:
      o[i,j] = 1

print()
print(o)

5
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


# Juego de Gato (Tres en Línea) - Python

## Reglas
- Tablero de 3x3.
- Dos jugadores: X y O.
- Gana quien logre una línea de 3 iguales (horizontal, vertical o diagonal).
- Si se llenan las 9 casillas y nadie gana, hay empate.


## Paso 1: Crear el tablero vacío

Creamos una matriz de 3x3 usando NumPy, rellena con espacios vacíos (`" "`), para representar un tablero sin jugadas.

In [ ]:
import numpy as np
tablero = np.full((3, 3), " ")

## Paso 2: Variables de control

Creamos el jugador actual y un contador de turnos.

In [ ]:
jugador_actual = "X"
turnos = 0

## Paso 3: Ciclo principal del juego

Mientras no se completen 9 turnos (máximo de jugadas posibles), pedimos una jugada, validamos la posición y la registramos.


In [ ]:
while turnos < 9:
    print("Tablero actual:")
    print(tablero)

    print(f"Turno del jugador {jugador_actual}")
    fila = int(input("Ingresa fila (0 a 2): "))
    col = int(input("Ingresa columna (0 a 2): "))

    if tablero[fila, col] == " ":
        tablero[fila, col] = jugador_actual
        turnos += 1
    else:
        print("Esa casilla ya está ocupada. Intenta otra vez.")
        continue

## Paso 4: Verificar victoria

Revisamos si el jugador actual logró hacer una línea horizontal, vertical o diagonal.

In [ ]:
while turnos < 9:
    print("Tablero actual:")
    print(tablero)

    print(f"Turno del jugador {jugador_actual}")
    fila = int(input("Ingresa fila (0 a 2): "))
    col = int(input("Ingresa columna (0 a 2): "))

    if tablero[fila, col] == " ":
        tablero[fila, col] = jugador_actual
        turnos += 1
    else:
        print("Esa casilla ya está ocupada. Intenta otra vez.")
        continue

# Revisar filas y columnas
    for i in range(3):
        if tablero[i, 0] == tablero[i, 1] == tablero[i, 2] != " ":
            print(tablero)
            print(f"¡Jugador {jugador_actual} gana por fila {i}!")
            turnos = 9
            break
        if tablero[0, i] == tablero[1, i] == tablero[2, i] != " ":
            print(tablero)
            print(f"¡Jugador {jugador_actual} gana por columna {i}!")
            turnos = 9
            break

    # Revisar diagonales
    if tablero[0, 0] == tablero[1, 1] == tablero[2, 2] != " ":
        print(tablero)
        print(f"¡Jugador {jugador_actual} gana por diagonal principal!")
        break
    if tablero[0, 2] == tablero[1, 1] == tablero[2, 0] != " ":
        print(tablero)
        print(f"¡Jugador {jugador_actual} gana por diagonal secundaria!")
        break

## Paso 5: Cambiar de jugador

Si nadie ganó aún, se cambia el jugador.


In [ ]:
while turnos < 9:
    print("Tablero actual:")
    print(tablero)

    print(f"Turno del jugador {jugador_actual}")
    fila = int(input("Ingresa fila (0 a 2): "))
    col = int(input("Ingresa columna (0 a 2): "))

    if tablero[fila, col] == " ":
        tablero[fila, col] = jugador_actual
        turnos += 1
    else:
        print("Esa casilla ya está ocupada. Intenta otra vez.")
        continue

# Revisar filas y columnas
    for i in range(3):
        if tablero[i, 0] == tablero[i, 1] == tablero[i, 2] != " ":
            print(tablero)
            print(f"¡Jugador {jugador_actual} gana por fila {i}!")
            turnos = 9
            break
        if tablero[0, i] == tablero[1, i] == tablero[2, i] != " ":
            print(tablero)
            print(f"¡Jugador {jugador_actual} gana por columna {i}!")
            turnos = 9
            break

    # Revisar diagonales
    if tablero[0, 0] == tablero[1, 1] == tablero[2, 2] != " ":
        print(tablero)
        print(f"¡Jugador {jugador_actual} gana por diagonal principal!")
        break
    if tablero[0, 2] == tablero[1, 1] == tablero[2, 0] != " ":
        print(tablero)
        print(f"¡Jugador {jugador_actual} gana por diagonal secundaria!")
        break

    if jugador_actual == "X":
        jugador_actual = "O"
    else:
        jugador_actual = "X"

## Paso 6: Empate

Si los turnos se completan sin que nadie gane, se declara empate.

In [ ]:
while turnos < 9:
    print("Tablero actual:")
    print(tablero)

    print(f"Turno del jugador {jugador_actual}")
    fila = int(input("Ingresa fila (0 a 2): "))
    col = int(input("Ingresa columna (0 a 2): "))

    if tablero[fila, col] == " ":
        tablero[fila, col] = jugador_actual
        turnos += 1
    else:
        print("Esa casilla ya está ocupada. Intenta otra vez.")
        continue

# Revisar filas y columnas
    for i in range(3):
        if tablero[i, 0] == tablero[i, 1] == tablero[i, 2] != " ":
            print(tablero)
            print(f"¡Jugador {jugador_actual} gana por fila {i}!")
            turnos = 9
            break
        if tablero[0, i] == tablero[1, i] == tablero[2, i] != " ":
            print(tablero)
            print(f"¡Jugador {jugador_actual} gana por columna {i}!")
            turnos = 9
            break

    # Revisar diagonales
    if tablero[0, 0] == tablero[1, 1] == tablero[2, 2] != " ":
        print(tablero)
        print(f"¡Jugador {jugador_actual} gana por diagonal principal!")
        break
    if tablero[0, 2] == tablero[1, 1] == tablero[2, 0] != " ":
        print(tablero)
        print(f"¡Jugador {jugador_actual} gana por diagonal secundaria!")
        break

    if jugador_actual == "X":
        jugador_actual = "O"
    else:
        jugador_actual = "X"

    if turnos == 9:
      print(tablero)
      print("¡Empate!")

Tablero actual:
[[' ' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]
Turno del jugador X
Ingresa fila (0 a 2): 0
Ingresa columna (0 a 2): 0
Tablero actual:
[['X' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]
Turno del jugador O
Ingresa fila (0 a 2): 0
Ingresa columna (0 a 2): 0
Esa casilla ya está ocupada. Intenta otra vez.
Tablero actual:
[['X' ' ' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]
Turno del jugador O
Ingresa fila (0 a 2): 0
Ingresa columna (0 a 2): 1
Tablero actual:
[['X' 'O' ' ']
 [' ' ' ' ' ']
 [' ' ' ' ' ']]
Turno del jugador X
Ingresa fila (0 a 2): 1
Ingresa columna (0 a 2): 1
Tablero actual:
[['X' 'O' ' ']
 [' ' 'X' ' ']
 [' ' ' ' ' ']]
Turno del jugador O
Ingresa fila (0 a 2): 0
Ingresa columna (0 a 2): 2
Tablero actual:
[['X' 'O' 'O']
 [' ' 'X' ' ']
 [' ' ' ' ' ']]
Turno del jugador X
Ingresa fila (0 a 2): 2
Ingresa columna (0 a 2): 2
[['X' 'O' 'O']
 [' ' 'X' ' ']
 [' ' ' ' 'X']]
¡Jugador X gana por diagonal principal!
